### PR TITLE
Bug 1798886 - Migrate code-coverage from AWS to GCP

### PR DESCRIPTION
**Pull request by MasterWayZ**

### CODE REVIEW

**Comment by marco-c** [comment]
@MasterWayZ I think we need to keep ".tar" in the task-boot command, but then use ".tar.zst" in the artifact section.
A bit like https://github.com/mozilla/task-boot/blob/dac41e22b908a6589e13894843d0ce9340bbbe6a/.taskcluster.yml#L75-L87.

**Comment by MasterWayZ** [comment]
Looks like the FirefoxCI job is passing now, I hope the rest of the changes are good.

**Comment by MasterWayZ** [comment]
Rebased.. we're green!

**Review by marco-c — APPROVED** [review]
> Rebased.. we're green!

\o/

Thanks!

**Pull request merged**
