### PR TITLE
Match the style of the logo with the menu

### PR DESCRIPTION
**Pull request by Crystal-RainSlide**
See issue https://github.com/mozilla/code-coverage/issues/488 for the details of this PR, and pull https://github.com/mozilla/code-coverage/pull/504 for another change preposed in the issue.

### CODE REVIEW

**Comment by marco-c** [comment]
I agree with the logo change, but why making the file list so narrow?

P.S.: Could you split the PR in two?

**Comment by Crystal-RainSlide** [comment]
> why making the file list so narrow?

To not to make the space between the file list so wide, so I shrink it into a size that is wider than phone screens.

Will widen the file list; and you are all free to edit my PR.

----

Maybe the best way is to put something else along with it, but, the history graph is horizontal, and nothing else left on the index page.

**Comment by marco-c** [comment]
OK, could you split the PR in two? I'd like to have separate logical changes :)

**Comment by Crystal-RainSlide** [comment]
Fine~

**Pull request merged**
