### PR TITLE
bot: Use Mercurial with Python 3

### LINKED ISSUE #332: Switch Mercurial to Python 3
https://github.com/mozilla/bugbug/commit/e023dc62ea3c44cb87591c6f4753fb071428cd84 :tada:

### PR DESCRIPTION
**Pull request by marco-c**
Fixes #332

### CODE REVIEW

**Comment by marco-c** [comment]
From ~104 MB to ~83,5 MB.

**Comment by marco-c** [comment]
robustcheckout doesn't work yet though, so we need to wait for it to be fixed before being able to merge this.

**Comment by La0** [comment]
:crying_cat_face: https://bugzilla.mozilla.org/show_bug.cgi?id=1604652

**Comment by marco-c** [comment]
The bug has been fixed!

**Pull request merged**
