### PR TITLE
Log exception downloading artifacts stack (#1260)

### PR DESCRIPTION
**Pull request by dmose**
I've done some basic testing in a Jupyter notebook, though not of the code in situ, as that's more work.  @marco-c I'm guessing this should be enough, but if not, let me know...

### CODE REVIEW

**Comment by marco-c** [comment]
The log from https://firefox-ci-tc.services.mozilla.com/tasks/YrjrX0GgR4qAKOnecqL-3g/runs/0/logs/public/logs/live.log shows that we logged `Exception while downloading coverage artifacts or cloning repository` from https://github.com/dmose/code-coverage/blob/4174dae70b4601d6282c5545ac4335063a60fc1d/bot/code_coverage_bot/hooks/base.py#L118, but we didn't log `Exception while downloading artifacts` from https://github.com/dmose/code-coverage/blob/4174dae70b4601d6282c5545ac4335063a60fc1d/bot/code_coverage_bot/artifacts.py#L184
This means the exception is happening earlier than where you're adding the new logging.
We should add it at https://github.com/dmose/code-coverage/blob/4174dae70b4601d6282c5545ac4335063a60fc1d/bot/code_coverage_bot/hooks/base.py#L118.

**Comment by dmose** [comment]
🤦 

OK, fixed, along with the linting and formatting issues.

I would have left the one in artifacts.py also , but mypy was giving a weird type error there, and I don't really have the bandwidth to debug it.

**Comment by dmose** [comment]
The failed add-on test in Community-TC appears to be some sort of CI issue to me, not a problem with the patch.

**Comment by dmose** [comment]
The front-end build failure also looks unrelated.

**Comment by marco-c** [comment]
> I would have left the one in artifacts.py also , but mypy was giving a weird type error there, and I don't really have the bandwidth to debug it.

That one should be unneeded, because ThreadPoolExecutorResult reraises the exception on exit: https://github.com/mozilla/code-coverage/blob/e7c8b8678dc281b2fc5344b087337000c22a9d97/bot/code_coverage_bot/utils.py#L88.
It is not happening in this specific case because we exit right away with os._exit.

**Review by marco-c — APPROVED** [review]
Thanks!

**Pull request merged**
