### PR TITLE
ISSUE #668 - Changed json-rev

### PR DESCRIPTION
**Pull request by mugunthanramesh**
Changed json-rev to json-automationrelevance. As json-rev returns complete diff and making latest version superslow

### CODE REVIEW

**Comment by mugunthanramesh** [comment]
Need to change the [tests](https://github.com/mozilla/code-coverage/blob/master/backend/tests/conftest.py#L138) present in backend

**Comment by shubham-y** [comment]
@mugunthanramesh Linting issue can be resolved

**Comment by mugunthanramesh** [comment]
@shubham-y ok will work on unit tests

**Comment by mugunthanramesh** [comment]
Any more test changes required ? Need guidance

**Comment by marco-c** [comment]
@mugunthanramesh you can see that the CI is failing, you can click on "Details" to navigate and see what the failures are

**Comment by marco-c** [comment]
@mugunthanramesh are you still interested on working on this?

**Comment by marco-c** [comment]
Feel free to reopen if you're still interested.

**Pull request closed without merging**
