### PR TITLE
Issue #97, add explanation box - 2nd PR

### LINKED ISSUE #97: Explain heuristics used for "uncovered files" in the UI
From Marco:

> For JavaScript files, the top-level code is always covered if the file is loaded, so we came up with a heuristic: a "zero coverage" file is a file which has at least one function and whose functions are all not covered.
> For C/C++ it's easier, as there's no top-level code and the code is always in functions. In this case, a "zero coverage" file is a file which has no covered lines.

It would great to put this in the UI somewhere for new users. Maybe add a "?" icon next to the uncovered files option that can show this explanation on hover.

### PR DESCRIPTION
**Pull request by InfTkm**
Fixed #97 and deleted trailing white spaces according to Taskcluster's log.
------------------------------------------------------------------------------------------------------
https://youtu.be/xmY6yLb7gu4
Here is a demo. Hopefully, I understood correctly where the question mark box should be.

Explanation of what I have done:

Line 59 in zero_coverage_report.js: sets the variable needs_explanation to true for the filter, completely_uncovered.
Line 138 - 146 in base.html: add the tooltip if the filter needs explanation (i.e. completely_uncovered).
At the end of style.scss: I added the CSS for the tooltip (i.e. popup explanation box) using SASS format.
Let me know if you have any questions or feedback. Thanks.

### CODE REVIEW

**Comment by InfTkm** [comment]
I didn't know that I could update the commits in a PR without creating a new one. Sorry about the duplicated PR.

**Comment by La0** [comment]
And here is a link to the [frontend from this build](https://community.taskcluster-artifacts.net/GtoMMq7_QYSSvAMyAgL5Bg/0/public/frontend/index.html#view=zero) so you can test.

**Comment by marco-c** [comment]
Yes, definitely better to rewrite that:
> For JavaScript, files with at least one function where all functions are uncovered. For C/C++/other languages, files which have no covered lines.

**Comment by La0** [comment]
@InfTkm Could you update the explanation text with the one mentionned above by Marco ?

**Comment by InfTkm** [comment]
@La0 Hi, the change is made, and you can see the result [here](http://cc.bitbit.cloud/#view=zero).
Thanks.

**Pull request merged**
